---
#-------------------------------
# Site Settings
title: Tropic Moon
logo: # You can add own logo. For example '/images/logo.png'.
#author: Jason Collins
#description: Clancy is a elegant portfolio theme for Jekyll.

#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: "Home"
      url: "/"
    # - title: "Blog"
    #   url: "/blog/"
    - title: "About"
      url: "/about/"
    - title: "Collab"
      url: "/collab/"
    # - title: "Contact"
    #   url: "/contact/"
    # - title: "Elements"
    #   url: "/elements/"

#-------------------------------
# Hero Settings
hero:
  hero__title: Hello, my name is Mike Laurence. I’m an engineer & photographer based in New York.
  hero__description: During the day, I build cool things for Reality Labs @ Meta. At night, I explore fantastical universes and soundscapes. I'm fascinated by futurism, space travel, simulation theory, and anything else that combines science and art.

#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Portfolio
  portfolio__gallery:
    - image: /assets/photos/2022-2-6 neon tropic moon.jpeg
      description: Ready for the tropics

    - image: /assets/photos/2022-1-8 dark tentacle sphere.jpeg
      #title: Cloaked in the outer wilds
      description: Cloaked in the outer wilds

    - image: /assets/photos/2022-1-11 a hill.jpeg
      title: Albina
      description: It may be junk, but it's still shelter

    - image: /assets/photos/2021-1-25 red mushroom field.jpeg
      description: Possibly psychadelic space mushrooms

    - image: /assets/photos/2022-1-17 beam him up sprite.jpeg
      title: Mark
      description: Invading one-by-one

    - image: /assets/photos/2020-4-4 tia in red.jpeg
      title: Tia
      description: Roses are red and sometimes dead

    - image: /assets/photos/2020-3-3 laying on grid B.jpeg
      description: On the grid, literally

    - image: /assets/photos/2018-12-16 messy-bodega-redshift.jpeg
      description: Big robot, small bodega

    # - image: /assets/photos/gallery-08.jpg
    #   title: Luca Bravo
    #   description: Worms eye view of city buildings <a href="https://unsplash.com/photos/a6x7YPiNxwI">Unsplash</a>

    # - image: /assets/photos/gallery-09.jpg
    #   title: Books and Laptop
    #   description: Silver laptop computer with two books on the top <a href="https://unsplash.com/photos/fFIAKABImf4">Unsplash</a>

#-------------------------------
# Subscribe Settings
# mailchimp:
#   mailchimp__title: Get updates and digital art inspiration # Add your Title
#   mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
#   mailchimp__button__text: Subscribe # Add your button text.
#   mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).

#-------------------------------
# Footer Settings
social:
  - {
      icon: "ion-logo-twitter",
      color: "#55acee",
      label: Twitter,
      link: "https://twitter.com/punkbot",
    }
  # - {
  #     icon: "ion-logo-facebook",
  #     color: "#3b5999",
  #     label: Facebook,
  #     link: "https://facebook.com",
  #   }
  # - {
  #     icon: "ion-logo-pinterest",
  #     color: "#bd081c",
  #     label: Pinterest,
  #     link: "https://pinterest.com",
  #   }
  # - {
  #     icon: "ion-logo-dribbble",
  #     color: "#ea4c89",
  #     label: Dribbble,
  #     link: "https://dribbble.com",
  #   }
  - {
      icon: "ion-logo-instagram",
      color: "#e4405f",
      label: Instagram,
      link: "https://instagram.com/tropicmoon.co",
    }
  # - {
  #     icon: "ion ion-logo-vimeo",
  #     color: "#1393cd",
  #     label: Vimeo,
  #     link: "https://vimeo.com",
  #   }

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contact form
  description: Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.
